services:
  postgres:
    image: postgres:16-alpine
    env_file: [./backend.env]
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: ghcr.io/santigf12/art-portfolio-backend
    env_file: [./backend.env]
    expose:
      - "1337"
    ports:
      - "1337:1337"
    volumes:
      - ./strapi-uploads:/app/public/uploads
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    image: ghcr.io/santigf12/art-portfolio-frontend
    env_file: [./frontend.env]
    environment:
      STRAPI_INTERNAL_URL: http://backend:1337
    ports:
      - "2697:3000"
    depends_on:
      - backend
    restart: unless-stopped
